name: Auto Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.9'
        os:
          - ubuntu-latest
        include:
          - os: macos-latest
            python: '3.9'
          - os: windows-latest
            python: '3.9'

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Print versions
        run: |
          python --version
          pip --version

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Unittest
        run: |
          python -m unittest discover tests/ --verbose
